[project]
name = "farsight"
version = "0.1.0"
description = "CLI-Based Recon and Threat Intelligence Framework"
authors = [
    {name = "FARSIGHT Team"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8,<4.0"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
